"""Template Model - AI-generated website templates"""
import uuid
from datetime import datetime
from sqlalchemy import Column, Integer, Text, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from ..database import Base


class Template(Base):
    """
    AI-generated website template for a business

    Stores HTML, CSS, and JavaScript content generated by GPT-4.
    Multiple variants (1-3) can be generated per business for user selection.
    Improvements_made field tracks what enhancements were applied vs original site.
    """
    __tablename__ = "templates"

    # Primary Key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Foreign Key to Business
    business_id = Column(UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"), nullable=False, index=True)

    # Template Content
    html_content = Column(Text, nullable=False)
    css_content = Column(Text, nullable=False)
    js_content = Column(Text, nullable=True)  # JS is optional

    # Improvement Tracking
    improvements_made = Column(JSONB, nullable=False, default=dict)
    """
    Structure example:
    {
        "performance": ["Optimized images", "Minified CSS"],
        "seo": ["Added meta tags", "Improved heading structure"],
        "accessibility": ["Added ARIA labels", "Improved contrast"],
        "design": ["Modern layout", "Responsive grid"]
    }
    """

    # Media Assets (Premium Templates)
    media_assets = Column(JSONB, nullable=True, default=None)
    """
    Structure example:
    {
        "images": [
            {
                "url": "https://images.unsplash.com/...",
                "alt": "Business image",
                "photographer": "John Doe",
                "photographer_url": "https://unsplash.com/@johndoe",
                "source": "Unsplash"
            },
            ...
        ],
        "hero_video": {
            "url": "https://videos.pexels.com/...",
            "poster": "https://images.pexels.com/...",
            "attribution": "Video by Jane Doe on Pexels",
            "duration": 15
        },
        "business_type": "restaurant"
    }
    """

    # Variant Tracking (1, 2, or 3)
    variant_number = Column(Integer, nullable=False)

    # Timestamp
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Relationship
    business = relationship("Business", back_populates="templates")

    def __repr__(self):
        return (f"<Template(id={self.id}, business_id={self.business_id}, "
                f"variant={self.variant_number}, generated_at={self.generated_at})>")


# Composite index for finding templates by business and variant
Index('ix_template_business_variant', Template.business_id, Template.variant_number)
