"""add_soft_delete_to_business

Revision ID: 59c59dec0a80
Revises: bb319a504bd2
Create Date: 2025-11-01 16:45:42.835119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c59dec0a80'
down_revision: Union[str, None] = 'bb319a504bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # Removed ENUM type changes - we use VARCHAR with CHECK constraints instead
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed ENUM type changes - we use VARCHAR with CHECK constraints instead
    op.drop_column('businesses', 'deleted_at')
    # ### end Alembic commands ###
